### PR TITLE
Transform gradients in strokes

### LINKED ISSUE #142: Strokes/outlines that have gradients sometimes don't render properly
### Expected Behavior

All SVG elements should appear on-stage the same way they do in the paint editor

### Actual Behavior

Strokes with gradients, in some cases, appear single-color on the stage:
image

This is blocking https://github.com/LLK/scratch-paint/pull/1004

### Steps to Reproduce

1. Save [gradientstroke.txt](https://github.com/LLK/scratch-svg-renderer/files/4679333/gradientstroke.txt) and change the file extension to .svg
2. Upload that file as a costume
3. Observe the difference between how the costume appears on-stage and how it appears in the paint editor

### Operating System and Browser

All

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves #142

### Proposed Changes

This PR extends the gradient-transforming logic in `transformStrokeWidths` to transform gradients not only in fills (as it previously did) but in strokes as well.

### Reason for Changes

Strokes can also have gradients (and https://github.com/LLK/scratch-paint/pull/1004 makes this much more likely). Previously, they weren't being taken into account when transforms were being applied.

### Test Coverage

Tested manually

### CODE REVIEW

File: src/transform-applier.js [hunk 1]
```diff
@@ -505,14 +505,42 @@ const _parseUrl = (value, windowRef) => {
...
+        // Need path bounds to transform gradient
+        const svgSpot = doc.createElement('span');
+        let bbox;
+        if (bboxForTesting) {
+            bbox = bboxForTesting;
+        } else {
+            try {
+                doc.body.appendChild(svgSpot);
+                const svg = SvgElement.set(windowRef.document.createElementNS(SvgElement.svg, 'svg'));
+                const path = SvgElement.set(windowRef.document.createElementNS(SvgElement.svg, 'path'));
```
Comment (adroitwhiz) [inline src/transform-applier.js]:
```suggestion
                const svg = SvgElement.set(doc.createElementNS(SvgElement.svg, 'svg'));
                const path = SvgElement.set(doc.createElementNS(SvgElement.svg, 'path'));
```
Should I include this code style enhancement as part of this PR?

File: src/transform-applier.js [hunk 2]
```diff
@@ -505,14 +505,42 @@ const _parseUrl = (value, windowRef) => {
...
         if (_isContainerElement(element)) {
             // Push fills and stroke width down to leaves
             if (element.attributes['stroke-width']) {
                 strokeWidth = element.attributes['stroke-width'].value;
             }
-            if (element.attributes && element.attributes.fill) {
-                fill = element.attributes.fill.value;
+            if (element.attributes) {
+                if (element.attributes.fill) fill = element.attributes.fill.value;
+                if (element.attributes.stroke) stroke = element.attributes.stroke.value;
```
Comment (adroitwhiz) [inline src/transform-applier.js:517]: Why are we checking if `element.attributes` exists here but not checking it in the previous if-block (`if (element.attributes['stroke-width'])`)?

File: src/transform-applier.js (hunk 1 above)
Comment (fsih) [reply src/transform-applier.js]: Sure

File: src/transform-applier.js (hunk 2 above)
Comment (fsih) [reply src/transform-applier.js:517]: It looks like element.attributes should exist if element.tagName exists, which is what we check for in _isContainerElement, except on Internet Explorer. So the if above would break on IE (but we don't support IE anyway)

File: src/transform-applier.js [hunk 3]
```diff
@@ -522,56 +550,42 @@ const transformStrokeWidths = function (svgTag, windowRef, bboxForTesting) {
...
-                    fill
+                    fill,
+                    stroke
                 );
             }
             element.removeAttribute('transform');
             element.removeAttribute('stroke-width');
             element.removeAttribute('fill');
+            element.removeAttribute('stroke');
         } else if (_isPathWithTransformAndStroke(element, strokeWidth)) {
```
Comment (fsih) [inline src/transform-applier.js:561]: We should double check if this code is working for stuff besides paths with strokes, like shapes

File: src/transform-applier.js [hunk 4]
```diff
@@ -568,8 +574,15 @@ const transformStrokeWidths = function (svgTag, windowRef, bboxForTesting) {
...
+                if (fillGradientId) {
+                    const newFillRef = _createGradient(fillGradientId, svgTag, bbox, matrix);
+                    if (newFillRef) fill = newFillRef;
+                }
+
+                if (strokeGradientId) {
+                    const newStrokeRef = _createGradient(strokeGradientId, svgTag, bbox, matrix);
+                    if (newStrokeRef) stroke = newStrokeRef;
+                }
             }
```
Comment (fsih) [inline src/transform-applier.js:586]: It seems like fillGradientId and strokeGradientId might be the same, and if they're the same, we should try not to make a duplicate definition (although I'm not sure if it hurts anything if we do have duplicates)

**Review by fsih — APPROVED** [review]
Looks good! Let's merge this after the deploy.
