### PR TITLE
Set stroke-linejoin and stroke-linecap to "round" for gradient strokes in 2.0 SVGs

### LINKED ISSUE #394: Vector costumes with rounded corners aren't imported correctly
### Expected Behavior

- Vector costumes in 2.0 and 3.0 should render the same

#### 2.0
image

#### 3.0
image

### Steps to Reproduce

https://scratch.mit.edu/projects/216633132
https://llk.github.io/scratch-gui/develop/#216633132

### Operating System and Browser

Mac OS 10.13.4  |  Version 65.0.3325.181 (Official Build) (64-bit)

/cc @fsih @cwillisf

### PR DESCRIPTION
**Pull request by adroitwhiz**
### Resolves

Resolves the rest of https://github.com/LLK/scratch-render/issues/194
Resolves https://github.com/LLK/scratch-paint/issues/394

### Proposed Changes

This PR adds another function to SvgRenderer which rounds all strokes with a gradient color. This function is only called for 2.0 ("version 2") SVGs. It also changes `SvgRenderer._collectElements` to allow the caller to optionally collect _all_ elements, which I used in the stroke-rounding function.

### Reason for Changes

In Scratch 2.0, for some inexplicable reason, all strokes with a gradient color have rounded joins and caps:
Peek 2019-04-26 16-49

This is relied upon in things like the text bubble from project [#186282308](https://llk.github.io/scratch-gui/develop/#186282308):

Current | This PR | Scratch 2.0
-|-|-
image | image | image

### CODE REVIEW

File: src/svg-renderer.js [hunk 1]
```diff
@@ -210,13 +212,13 @@ class SvgRenderer {
     }
 
     /**
-     * @param {string} tagName svg tag to search for
+     * @param {string} [tagName] svg tag to search for
      * @return {Array} a list of elements with the given tagname in _svgTag
      */
-    _collectElements (tagName) {
+    _collectElements (tagName = null) {
```
Comment (fsih) [inline src/svg-renderer.js]: Why add collecting tagName = null elements here?

File: src/svg-renderer.js [hunk 2]
```diff
@@ -292,6 +294,25 @@ class SvgRenderer {
...
 
+    /**
+     * Find all instances of a URL-referenced `stroke` in the svg. In 2.0, all gradient strokes
+     * have a round `stroke-linejoin` and `stroke-linecap`... for some reason.
+     */
+    _setGradientStrokeRoundedness () {
+        const elements = this._collectElements();
+
+        for (const elt of elements) {
+            if (elt.getAttribute) {
```
Comment (fsih) [inline src/svg-renderer.js]: Does it make sense to add this filter to _collectElements?

Comment (adroitwhiz) [reply src/svg-renderer.js]: Done

File: src/svg-renderer.js (hunk 1 above)
Comment (adroitwhiz) [reply src/svg-renderer.js]: If a tag name is not passed, it will default to `null`, which line 221 checks. I can remove this and just check if `typeof tagName === undefined`.

**Review by fsih — APPROVED** [review]
LG, thanks!
